name: itmo-devops-sem1-project

include:
  - docker-compose/postgres.yml

services:
  server:
    extends:
      file: docker-compose/server.yml
      service: server
    image: itmo508541/itmo-devops-sem1-project:latest
